---
--
title: "Toolik_gth89_Sila Flux Cleaning"
output:
html_document: default
df_print: paged
pdf_document: default
date: "2025-07-16"
---


```{r, warning=FALSE}
rm(list = ls())
Sys.setenv(TZ = "UTC")
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'C:/Users/klynoe/Documents/toolik/R_outputs') #use this to set your directory

library(data.table)
library(ggplot2)
library(cowplot)
library(openair)
library(plotrix)
library(signal)
library(svMisc)
library(zoo)
library(stringr)
library(plyr)
library(dplyr)



```

```{r, warning=FALSE}

df = read.csv('C:/Users/klynoe/Documents/toolik/R_outputs/toolik_met_flux_merged_aligned_2025_2026.csv')


df$TIMESTAMP <- as.POSIXct(df$TIMESTAMP, format = "%Y-%m-%d %H:%M", tz = "UTC")
#df$ts <- as.POSIXct(df$ts, format = "%Y-%m-%d %H:%M", tz = "UTC")
# Replace specific missing value indicators with NA
df[df == -9999] <- NA
df[df == -7999] <- NA


#timestamp_cutoff <- as.POSIXct("2025-05-01 14:00", format = "%Y-%m-%d %H:%M", tz = "UTC")
#df <- df %>%
#  dplyr::filter(TIMESTAMP >= timestamp_cutoff)


# Create a complete sequence of timestamps at 30-minute intervals
tsdf <- data.frame(TIMESTAMP = seq(
  from = min(df$TIMESTAMP),
  to = max(df$TIMESTAMP),
  by = 60*30
))



df = merge(tsdf,df,by = 'TIMESTAMP',all.x = T)




#summary(df)

```

```{r, warning=FALSE}
biomet_dates <- c('2025-05-01', '2026-08-01')
#biomet_dates <- c('2024-10-30', '2024-12-01')
```

# Air T 
```{r, warning=FALSE}
#First we need to just convert from Kelvin to degrees C
df$TA_2_1_1_1_1 = ifelse(df$TA_2_1_1_1_1 > 200,df$TA_2_1_1_1_1 - 273.15,df$TA_2_1_1_1_1)

ggplot(data = df)+
  geom_point(aes(TIMESTAMP, TA_2_1_1_1_1),col='black')+
  scale_y_continuous(limits = c(-40,40),
                     expression('Air Temperature ('*Celsius*')'))+
  scale_x_datetime(limits = as.POSIXct(biomet_dates))



ggplot(data = df)+
  geom_point(aes(TIMESTAMP,TA_2_1_1_1_1),col='black')+
  scale_y_continuous(limits = c(-40,40),
                      expression('Air Temperature ('*Celsius*')'))+
   scale_x_datetime(limits = as.POSIXct(biomet_dates))
```


## Limits
```{r, warning=FALSE}
hist(df$TA_2_1_1_1_1,breaks=100)
plot(df$TIMESTAMP,df$TA_2_1_1_1_1,ylim = c(-50,50));abline(h=-50, col= 'red');abline(h=50, col='red')
TA_2_1_1_1_1.limits = replace(df$TA_2_1_1_1_1, df$TA_2_1_1_1_1 < -50 | df$TA_2_1_1_1_1 > 50,NA)
hist(TA_2_1_1_1_1.limits,breaks=100)
plot(TA_2_1_1_1_1.limits)

df$TA_2_1_1_1_1.c = TA_2_1_1_1_1.limits

df$TA_2_1_1_1_1.c[ df$TIMESTAMP %between% as.POSIXct(
  c("2025-12-03 09:30", "2025-12-12 12:00"), tz = "UTC")] = NA # HMP malfunction so just wiping this

plot(df$TA_2_1_1_1_1.c)
```


#Relative Humidity

```{r,warning=FALSE}
ggplot(data = df)+
  geom_point(aes(TIMESTAMP,RH_19_3_1_1_1),col='black')+
  scale_y_continuous(#limits = c(20,100),
                     expression('Relative Humidity ('*percent*')'))+
 scale_x_datetime(limits = as.POSIXct(biomet_dates))
```


## Limits
```{r,warning=FALSE}
RH.limits = df$RH_19_3_1_1_1

#RH_19_3_1_1_1.limits = ifelse(df$RH_19_3_1_1_1 > 0 & df$TIMESTAMP <= '2022-9-23',NA, RH_19_3_1_1_1.limits)

df$RH.c = RH.limits

df$RH.c[ df$TIMESTAMP %between% as.POSIXct(
 c("2025-12-03 09:30", "2025-12-12 12:00"), tz = "UTC")] = NA # HMP malfunction so just wiping this

ggplot(data = df)+
  geom_point(aes(TIMESTAMP,RH.c),col='black')+
  scale_y_continuous(limits = c(5,105),
                     expression('Relative Humidity ('*percent*')'))+
  scale_x_datetime(limits = as.POSIXct(biomet_dates))
```


# Barometric Pressure 
```{r, warning=FALSE}

cutoff_date <- as.POSIXct("2026-05-01 00:00:00", tz = "UTC")
lbl_y <- expression('Barometric Pressure ('*kPa*')')

# --- SAFEGUARD: Back up original columns on first run to allow infinite reruns ---
if (!exists("air_p_mean_backup", envir = .GlobalEnv)) air_p_mean_backup <<- df$air_p_mean
if (!exists("PA_4_2_1_1_1_backup", envir = .GlobalEnv)) PA_4_2_1_1_1_backup <<- df$PA_4_2_1_1_1

# Always reset active columns to raw data at the start of execution
df$air_p_mean   <- air_p_mean_backup
df$PA_4_2_1_1_1 <- PA_4_2_1_1_1_backup

# =========================================================================
# 1. CLEANING & PLOTTING: air_p_mean
# =========================================================================
#
ggplot(df) + geom_point(aes(TIMESTAMP, air_p_mean)) + scale_y_continuous(name = lbl_y) + scale_x_datetime(limits = as.POSIXct(biomet_dates))

# Unit conversion step
df$air_p_mean <- ifelse(df$air_p_mean > 97000, df$air_p_mean / 1000, df$air_p_mean)
df$air_p_mean <- ifelse(df$air_p_mean > 87000, df$air_p_mean / 1000, df$air_p_mean)

# Plot 2: Scaled view
ggplot(df) + geom_point(aes(TIMESTAMP, air_p_mean)) + scale_y_continuous(limits = c(0, 200), name = lbl_y)

# Tenfold correction step
df$air_p_mean <- ifelse(df$air_p_mean > 150, df$air_p_mean / 10, df$air_p_mean)

# 
ggplot(df) + geom_point(aes(TIMESTAMP, air_p_mean)) + scale_y_continuous(limits = c(86, 94), name = lbl_y)
hist(df$air_p_mean, breaks = 10)
ggplot(df) + geom_point(aes(TIMESTAMP, air_p_mean)) + scale_y_continuous(limits = c(85, 100), name = lbl_y)

# Boundaries filter
air_p_mean.limits <- ifelse(df$air_p_mean > 110 | df$air_p_mean < 85, NA, df$air_p_mean)
df$air_p_mean.c      <- air_p_mean.limits

# Plot 6: Cleaned with limits
ggplot(df) + geom_point(aes(TIMESTAMP, air_p_mean.limits)) + geom_hline(yintercept = c(87, 96), col = 'red') + scale_y_continuous(limits = c(85, 100), name = lbl_y)


# =========================================================================
# 2. CLEANING & PLOTTING: PA_4_2_1_1_1
# =========================================================================
# 
ggplot(df) + geom_point(aes(TIMESTAMP, PA_4_2_1_1_1)) + scale_y_continuous(name = lbl_y)

# Unit conversion step
df$PA_4_2_1_1_1 <- ifelse(df$PA_4_2_1_1_1 > 97000, df$PA_4_2_1_1_1 / 1000, df$PA_4_2_1_1_1)

# Plot 8: Scaled view
ggplot(df) + geom_point(aes(TIMESTAMP, PA_4_2_1_1_1)) + scale_y_continuous(limits = c(0, 1100), name = lbl_y)

# Tenfold correction step
df$PA_4_2_1_1_1 <- ifelse(df$PA_4_2_1_1_1 > 150, df$PA_4_2_1_1_1 / 10, df$PA_4_2_1_1_1)

# 
ggplot(df) + geom_point(aes(TIMESTAMP, PA_4_2_1_1_1)) + scale_y_continuous(limits = c(0, 140), name = lbl_y)
hist(df$PA_4_2_1_1_1, breaks = 100)
ggplot(df) + geom_point(aes(TIMESTAMP, PA_4_2_1_1_1)) + scale_y_continuous(limits = c(85, 110), name = lbl_y)

# Boundaries filter
PA_4_2_1_1_1.limits <- ifelse(df$PA_4_2_1_1_1 > 110 | df$PA_4_2_1_1_1 < 85, NA, df$PA_4_2_1_1_1)
df$PA_4_2_1_1_1.c      <- PA_4_2_1_1_1.limits

# Plot 12: Cleaned with limits
ggplot(df) + geom_point(aes(TIMESTAMP, PA_4_2_1_1_1.limits)) + geom_hline(yintercept = c(86, 106), col = 'red') + scale_y_continuous(limits = c(85, 110), name = lbl_y)


# =========================================================================
# 3. MERGE TIMELINES CHRONOLOGICALLY
# =========================================================================
combined_pressure <- ifelse(df$TIMESTAMP < cutoff_date, df$air_p_mean.c, df$PA_4_2_1_1_1.c)

# Plot 13: Final master dataset visualization
ggplot(df) + geom_point(aes(TIMESTAMP, combined_pressure), alpha = 0.5) + geom_vline(xintercept = cutoff_date, col = 'blue', linetype = 'dashed') + scale_y_continuous(limits = c(85, 97), name = lbl_y) + labs(title = "All Pressure")

```

#Soil Heat Flux
```{r, warning=FALSE}

# 1. Filter data based on your cutoff date
df_filtered <- subset(df, TIMESTAMP >= as.POSIXct("2025-07-02 00:00:00", tz = "UTC"))

# 2. Plot using your original wide structure
ggplot(data = df_filtered) +
  geom_point(aes(TIMESTAMP, SHF_6_37_1_1_1, col = 'SHF 1')) +
  geom_point(aes(TIMESTAMP, SHF_6_37_2_1_1, col = 'SHF 2')) +
  scale_y_continuous(
    name = expression('Soil Heat Flux ('*W/m^2*')'),
    limits = c(-80, 190)
  ) +
  scale_color_manual(
    name = NULL,
    values = c('SHF 1' = 'red', 'SHF 2' = 'black')
  ) +
  scale_x_datetime(
    date_breaks = "2 months", 
    date_labels = "%b %Y"
  ) +
  theme_minimal()

```

## SHF1
```{r, warning=FALSE}
# -------------------------------
# -------------------------------
cutoff_time = as.POSIXct("2025-07-01 11:30", tz = "UTC")

df$SHF_6_37_1_1_1.c <- df$SHF_6_37_1_1_1

# FIX: Combined all three conditions inside brackets, assigned NA outside
df$SHF_6_37_1_1_1.c[df$SHF_6_37_1_1_1 < -55 | df$SHF_6_37_1_1_1 > 190 | df$TIMESTAMP < cutoff_time] <- NA

# -------------------------------
# 2. Optional: check with histogram and plot
# -------------------------------
hist(df$SHF_6_37_1_1_1.c, breaks = 100)

plot(df$TIMESTAMP, df$SHF_6_37_1_1_1.c, type = "l", ylim = c(-50, 200))
abline(h = -55, col = "red")
abline(h = 190, col = "red")
abline(v = cutoff_time, col = "blue", lty = 2) # show cutoff



```

## SHF2
```{r, warning=FALSE}
## -------------------------------
# SHF 2: limits + cutoff time
# -------------------------------
cutoff_time <- as.POSIXct("2025-07-01 11:30", tz = "UTC")

df$SHF_6_37_2_1_1.c <- df$SHF_6_37_2_1_1

# FIX: Added missing OR operator, uncommented timestamp, assigned NA outside brackets
df$SHF_6_37_2_1_1.c[df$SHF_6_37_2_1_1 < -75 | df$SHF_6_37_2_1_1 > 150 | df$TIMESTAMP < cutoff_time] <- NA

# -------------------------------
# Verification Plots
# -------------------------------
hist(df$SHF_6_37_2_1_1.c, breaks = 100)

plot(df$TIMESTAMP, df$SHF_6_37_2_1_1.c, type = "l", ylim = c(-80, 165))
abline(h = -75, col = "red")
abline(h = 150, col = "red")
abline(v = cutoff_time, col = "blue", lty = 2) # Now active to show cutoff line


```
##SHF

```{r, warning=TRUE}
ggplot(data = df)+
  geom_point(aes(TIMESTAMP,SHF_6_37_1_1_1.c,col='SHF 1'))+
  geom_point(aes(TIMESTAMP,SHF_6_37_2_1_1.c,col='SHF 2'))+
 
  scale_y_continuous(limits = c(-30,100),
                     expression ('Soil Heat Flux ('*W/m^2*')'))+
  scale_color_manual(values = c('red','black','brown'))+
  scale_x_datetime(limits = as.POSIXct(biomet_dates))

```



# PAR IN 
```{r, warning=FALSE}
ggplot(data = df)+
  geom_point(aes(TIMESTAMP,PPFD_7_21_1_1_1),col='black')+
  scale_y_continuous(limits = c(-25,2000),
                     expression('PAR ('*mu*mol/m^2/s*')'))

ggplot(data = df)+
  geom_point(aes(TIMESTAMP,PPFD_7_21_1_1_1),col='black')+
  scale_y_continuous(limits = c(-25,2000),
                     expression('PAR ('*mu*mol/m^2/s*')'))
 # scale_x_datetime(limits =as.POSIXct(c( '2025-05-01', '2025-12-15'),format="%F"))
```

```{r, warning=FALSE}
summary(df$PPFD_7_21_1_1_1)
hist(df$PPFD_7_21_1_1_1,breaks=100)
plot(df$TIMESTAMP,df$PPFD_7_21_1_1_1,ylim = c(0,1850));abline(h=1750, col= 'red');abline(h=0, col='red')
PPFD_7_21_1_1_1.limits = replace(df$PPFD_7_21_1_1_1, df$PPFD_7_21_1_1_1 < 0 | df$PPFD_7_21_1_1_1 > 1750,NA)
hist(PPFD_7_21_1_1_1.limits,breaks=100)
plot(PPFD_7_21_1_1_1.limits)

df$PPFD_7_21_1_1_1.c = PPFD_7_21_1_1_1.limits
```

PAR OUT
```{r, warning=FALSE}
ggplot(data = df)+
  geom_point(aes(TIMESTAMP,PPFDR_7_23_1_1_1),col='black')+
  scale_y_continuous(limits = c(-25,2000),
                     expression('PAR ('*mu*mol/m^2/s*')'))

ggplot(data = df)+
  geom_point(aes(TIMESTAMP,PPFDR_7_23_1_1_1),col='black')+
  scale_y_continuous(limits = c(-25,2000),
                     expression('PAR ('*mu*mol/m^2/s*')'))
  #scale_x_datetime(limits =as.POSIXct(c( '2025-05-01', '2025-12-15'),format="%F"))
```

```{r, warning=FALSE}
summary(df$PPFDR_7_23_1_1_1)
hist(df$PPFDR_7_23_1_1_1,breaks=100)
plot(df$TIMESTAMP,df$PPFDR_7_23_1_1_1,ylim = c(0,1850));abline(h=1750, col= 'red');abline(h=0, col='red')
PPFDR_7_23_1_1_1.limits = replace(df$PPFDR_7_23_1_1_1, df$PPFDR_7_23_1_1_1 < 0 | df$PPFDR_7_23_1_1_1 > 1750,NA)
hist(PPFDR_7_23_1_1_1.limits,breaks=100)
plot(PPFDR_7_23_1_1_1.limits)

df$PPFDR_7_23_1_1_1.c = PPFDR_7_23_1_1_1.limits
```

# Net Radiation 
```{r, warning=FALSE}
ggplot(data = df)+
  geom_point(aes(TIMESTAMP, RN_6_5_1_1_1),col='black')+
  scale_y_continuous(limits = c(-125,550),
                     expression('Net Radiation ('*W/m^2*')'))
```

```{r, warning=FALSE}
hist(df$RN_6_5_1_1_1,breaks=100)
plot(df$TIMESTAMP,df$RN_6_5_1_1_1,ylim = c(-400,850));abline(h=835,col= 'red');abline(h=-300, col='red')
RN_6_5_1_1_1.limits = replace(df$RN_6_5_1_1_1, df$RN_6_5_1_1_1 < -300 | df$RN_6_5_1_1_1 > 835,NA)
hist(RN_6_5_1_1_1.limits,breaks=100)
plot(df$TIMESTAMP,RN_6_5_1_1_1.limits)
df$RN_6_5_1_1_1.c = RN_6_5_1_1_1.limits

```

# Shortwave in 
```{r, warning=FALSE}
ggplot(data = df)+
  geom_point(aes(TIMESTAMP,SWIN_6_10_1_1_1))+
  scale_y_continuous(#limits = c(-10,1000),
                     expression('Shortwave In ('*W/m^2*')'))
```

```{r, warning=FALSE}
hist(df$SWIN_6_10_1_1_1,breaks=100)
plot(df$TIMESTAMP,df$SWIN_6_10_1_1_1,ylim = c(0,1000));abline(h=900,col= 'red');abline(h=-1, col='red')
SWIN_6_10_1_1_1.limits <- df$SWIN_6_10_1_1_1
SWIN_6_10_1_1_1.limits[df$SWIN_6_10_1_1_1 < 0] <- 0
hist(SWIN_6_10_1_1_1.limits,breaks=100)
plot(df$TIMESTAMP,SWIN_6_10_1_1_1.limits)
df$SWIN_6_10_1_1_1.c = SWIN_6_10_1_1_1.limits
```


# Shortwave out 
```{r, warning=FALSE}
ggplot(data = df)+
  geom_point(aes(TIMESTAMP,SWOUT_6_11_1_1_1))+
  scale_y_continuous(limits = c(-10,550),
                     expression('Shortwave Out ('*W/m^2*')'))+
  scale_x_datetime(limits = as.POSIXct(biomet_dates))
```

```{r, warning=FALSE}
hist(df$SWOUT_6_11_1_1_1,breaks=100)
plot(df$TIMESTAMP,df$SWOUT_6_11_1_1_1,ylim = c(0,800));abline(h=700,col= 'red');abline(h=-1, col='red')
SWOUT_6_11_1_1_1.limits <- df$SWOUT_6_11_1_1_1
SWOUT_6_11_1_1_1.limits[df$SWOUT_6_11_1_1_1 < 0] <- 0
hist(SWOUT_6_11_1_1_1.limits,breaks=100)
plot(df$TIMESTAMP,SWOUT_6_11_1_1_1.limits)
df$SWOUT_6_11_1_1_1.c = SWOUT_6_11_1_1_1.limits

```

# Albedo 
```{r, warning=FALSE}
albedo = df$SWOUT_6_11_1_1_1.c / df$SWIN_6_10_1_1_1.c

ggplot(data = df)+
  geom_point(aes(TIMESTAMP,albedo))+
  scale_y_continuous(limits = c(-1,2),
                     expression('Albedo'))+
  scale_x_datetime(limits = as.POSIXct(biomet_dates))

albedo.limits = replace(albedo, albedo < .05 | albedo > 1,NA)


ggplot(data = df)+
  geom_point(aes(TIMESTAMP,albedo.limits))+
  scale_y_continuous(limits = c(-.5,1.5),
                     expression('Albedo'))+
  scale_x_datetime(limits = as.POSIXct(biomet_dates))


```

```{r, warning=FALSE}
f = albedo.limits # first make a new flux vector to apply the above filters
# prepare the inputs for a zero-phase (forward and reverse) filter  
ind       = which(complete.cases(f))   # first save the index of all the NAs
b         = rep(1,8)/8                 # moving average coefficient
a         = 1                          # coefficient of the ARMA filter
mad_i    = filtfilt(b, a, na.omit(f)) #create a forward and reverse ARMA filter
mad_filt = f                          # make a copy of the full fluxes again
mad_filt[ind] = mad_i                # apply the filter where the real data exist

n = 7*48 # set the length of the rolling filter, 48 half hours in day * x days
roll.mad = rollapply(data = mad_filt,
                     width = n,
                     FUN = mad,
                     partial = TRUE,
                     na.rm = T,
                     fill = NA)  #create a rolling MAD or sd or other
roll.mad[is.na(mad_filt)] = NA  #make NA values where NAs exist in the real data

ggplot(df)+geom_hline(yintercept = 0)+
  geom_point(aes(TIMESTAMP,albedo.limits,col='Albedo'))+
  geom_line(aes(TIMESTAMP,mad_filt,col='Filter'))+
  geom_line(aes(TIMESTAMP,roll.mad,col='MAD'))+
  scale_y_continuous(limits = c(0,1))+
  scale_x_datetime(limits = as.POSIXct(biomet_dates,format="%F"))+
  scale_color_manual(values=c('black','yellow','red'))
```


```{r, warning=FALSE}
#adjust this value (N) to tweak how many MADs to be away from the norm
N = 4

#Add clean value to dataframe (_.c)

df$ALB_1_1_1.c = ifelse(abs(albedo.limits - mad_filt) > (N * roll.mad),NA,albedo.limits)

#Compare cleaned vs. uncleaned


ggplot(df)+geom_hline(yintercept = 0)+
  geom_point(aes(TIMESTAMP,albedo.limits,col='Uncleaned'))+
  geom_point(aes(TIMESTAMP,df$ALB_1_1_1.c,col='Cleaned'))+
  scale_y_continuous(limits = c(0,1))+
  scale_color_manual(values=c('black','red'))   #scale_x_datetime(limits=as.POSIXct(c('2024-07-25','2024-12-01'),format="%F"))+
 


```

# Longwave In 
```{r, warning=FALSE}
ggplot(data = df)+
  geom_point(aes(TIMESTAMP,LWIN_6_14_1_1_1))+
  scale_y_continuous(limits = c(-250,550),
                     expression('Longwave In ('*W/m^2*')'))+
  scale_x_datetime(limits = as.POSIXct(biomet_dates))

```

```{r, warning=FALSE}
hist(df$LWIN_6_14_1_1_1,breaks=100)
plot(df$TIMESTAMP,df$LWIN_6_14_1_1_1,ylim = c(80,750));abline(h=450, col= 'red');abline(h=90, col='red')
LWIN_6_14_1_1_1.limits = replace(df$LWIN_6_14_1_1_1, df$LWIN_6_14_1_1_1 < 80 | df$LWIN_6_14_1_1_1 > 450,NA)
hist(LWIN_6_14_1_1_1.limits,breaks=100)

ggplot(data = df)+
  geom_point(aes(TIMESTAMP,LWIN_6_14_1_1_1.limits))+
  scale_y_continuous(limits = c(-250,550),
                     expression('Longwave In ('*W/m^2*')'))+
  scale_x_datetime(limits = as.POSIXct(biomet_dates))

df$LWIN_6_14_1_1_1.c = LWIN_6_14_1_1_1.limits

```


# Longwave out 
```{r, warning=FALSE}
ggplot(data = df)+
  geom_point(aes(TIMESTAMP,LWOUT_6_15_1_1_1))+
  scale_y_continuous(limits = c(-100,500),
                     expression('Longwave Out ('*W/m^2*')'))+
  scale_x_datetime(limits = as.POSIXct(biomet_dates))
```

```{r, warning=FALSE}
hist(df$LWOUT_6_15_1_1_1,breaks=100)
plot(df$TIMESTAMP,df$LWOUT_6_15_1_1_1,ylim = c(80,750));abline(h=550, col= 'red');abline(h=85, col='red')
LWOUT_6_15_1_1_1.limits = replace(df$LWOUT_6_15_1_1_1, df$LWOUT_6_15_1_1_1 < 85 | df$LWOUT_6_15_1_1_1 > 550,NA)
hist(LWOUT_6_15_1_1_1.limits,breaks=100)
plot(LWOUT_6_15_1_1_1.limits)
df$LWOUT_6_15_1_1_1.c = LWOUT_6_15_1_1_1.limits
```


# Convert Soil Temps in Kelvin to Celcius
```{r, warning=FALSE}

ts_columns <- names(df)[grepl("TS", names(df))]

for (col in ts_columns) {
  df[[col]] <- ifelse(df[[col]] > 150, df[[col]] - 273.15, df[[col]])
}

```


# HERE ALL SOILTHERMS ARE AT 15 CM
# 8 cm
```{r, warning=FALSE}
ggplot(data = df)+ theme_bw()+ geom_hline(yintercept = 0)+
  geom_point(aes(TIMESTAMP, TS_2_38_1_1_1, col = '8 cm'))+
  scale_y_continuous(limits = c(-18,15),
                     expression('Therms Soil T ('*C*')'))

df$TS_2_38_1_1_1[df$TIMESTAMP == as.POSIXct("2025-12-03 10:00:00")] <- NA # take out bad reading
df$TS_2_38_1_1_1[df$TIMESTAMP == as.POSIXct("2026-04-28 11:00:00")] <- NA # take out bad reading  
df$TS_2_38_1_1_1[df$TIMESTAMP == as.POSIXct("2026-03-04 15:30:00")] <- NA # take out bad reading  

TS_2_38_1_1_1.limits = df$TS_2_38_1_1_1

df$TS_2_38_1_1_1.c = TS_2_38_1_1_1.limits

ggplot(data = df)+ theme_bw()+ geom_hline(yintercept = 0)+
  geom_line(aes(TIMESTAMP, TS_2_38_1_1_1.c, col = '8 cm'))

plot(df$TS_2_38_1_1_1.c)


```


#18 Cm depth Therm

```{r, warning=FALSE}

ggplot(data = df)+ theme_bw()+ geom_hline(yintercept = 0)+
  geom_line(aes(TIMESTAMP, TS_2_38_2_1_1, col = '18 cm'))+
  scale_x_datetime(limits = as.POSIXct(biomet_dates))

df$TS_2_38_2_1_1[df$TIMESTAMP == as.POSIXct("2025-12-03 10:00:00")] <- NA # take out bad reading
df$TS_2_38_2_1_1[df$TIMESTAMP == as.POSIXct("2026-04-28 11:00:00")] <- NA # take out bad reading
df$TS_2_38_2_1_1[df$TIMESTAMP == as.POSIXct("2026-03-04 15:30:00")] <- NA # take out bad reading
TS_2_38_2_1_1.limits = df$TS_2_38_2_1_1

df$TS_2_38_2_1_1.c = TS_2_38_2_1_1.limits

ggplot(data = df)+ theme_bw()+ geom_hline(yintercept = 0)+
  geom_line(aes(TIMESTAMP, TS_2_38_2_1_1.c, col = '18 cm'))
#+
 # scale_x_datetime(limits = as.POSIXct(c("2024-07-25",'2024-12-01')))

plot(df$TS_2_38_2_1_1.c)
```

#28 Cm depth Therm

```{r, warning=FALSE}

# Ensure df is a data.table
setDT(df)

# 1. First, build the combined master column (.c) using fcoalesce
# This bridges the old data with the new data seamlessly
df[, TS_2_38_2_2_1 := fcoalesce(TS_2_38_2_2_1, TS_2_38_23_1_1)]

ggplot(data = df)+ theme_bw()+ geom_hline(yintercept = 0)+
  geom_line(aes(TIMESTAMP, TS_2_38_2_2_1, col = '28 cm'))+
  scale_x_datetime(limits = as.POSIXct(biomet_dates))

# 2. NOW clean the outliers directly from the final combined column (.c)
# This safely catches both the 2025 and 2026 spikes in one place
df[TIMESTAMP == as.POSIXct("2025-12-03 10:00:00", tz = "UTC"), TS_2_38_2_2_1 := NA]
df[TIMESTAMP == as.POSIXct("2026-04-28 11:00:00", tz = "UTC"), TS_2_38_2_2_1 := NA]
df[TIMESTAMP == as.POSIXct("2026-03-04 15:30:00", tz = "UTC"), TS_2_38_2_2_1 := NA]

TS_2_38_2_2_1.limits = df$TS_2_38_2_2_1

df$TS_2_38_2_2_1.c = TS_2_38_2_2_1.limits


# 3. Generate the clean plot
ggplot(data = df) + 
  theme_bw() + 
  geom_hline(yintercept = 0) + 
  geom_line(aes(x = TIMESTAMP, y = TS_2_38_2_2_1.c, col = '28 cm')) +
  scale_x_datetime(limits = as.POSIXct(biomet_dates))


plot(df$TS_2_38_2_2_1.c)
```


# All soil therms
```{r, warning=FALSE}
ggplot(data = df)+ theme_bw()+
  geom_hline(yintercept = 0)+
  geom_line(aes(TIMESTAMP,TS_2_38_1_1_1.c,color='08 cm'))+
  geom_line(aes(TIMESTAMP,TS_2_38_2_1_1.c,color='18 cm'))+
  geom_line(aes(TIMESTAMP,TS_2_38_2_2_1.c,color='28 cm'))
  
 # scale_x_datetime(biomet_dates)
```


# Volumetric Water Content
```{r, warning=FALSE}

# Ensure df is treated cleanly as a data.table
setDT(df)

# 1. Strip out the bad readings first using explicit UTC timestamps
df[TIMESTAMP == as.POSIXct("2025-12-03 10:00:00", tz = "UTC"), SWC_12_36_1_1_1 := NA]
df[TIMESTAMP == as.POSIXct("2025-12-03 10:00:00", tz = "UTC"), SWC_12_36_2_1_1 := NA]
df[TIMESTAMP == as.POSIXct("2025-12-03 10:00:00", tz = "UTC"), SWC_12_36_3_1_1 := NA]
df[TIMESTAMP == as.POSIXct("2026-04-28 11:00:00", tz = "UTC"), SWC_12_36_1_1_1 := NA]
df[TIMESTAMP == as.POSIXct("2026-04-28 11:00:00", tz = "UTC"), SWC_12_36_2_1_1 := NA]
df[TIMESTAMP == as.POSIXct("2026-04-28 11:00:00", tz = "UTC"), SWC_12_36_3_1_1 := NA]


# 2. Set up your cleaned plotting variables (.c)
df[, SWC_12_36_1_1_1.c := SWC_12_36_1_1_1]
df[, SWC_12_36_2_1_1.c := SWC_12_36_2_1_1]

# 3. PRIORITY FIX: Prioritize the 3_1_1 column, fill historical gaps with 2_2_1
df[, SWC_12_36_3_1_1.c := fcoalesce(SWC_12_36_3_1_1, SWC_12_36_2_2_1)]

# 4. Generate the correct plot using the 3_1_1.c master variable
ggplot(data = df) + 
  geom_point(aes(TIMESTAMP, SWC_12_36_1_1_1.c * 100, col = 'SWC 08cm')) + 
  geom_point(aes(TIMESTAMP, SWC_12_36_2_1_1.c * 100, col = 'SWC 18cm')) + 
  geom_point(aes(TIMESTAMP, SWC_12_36_3_1_1.c * 100, col = 'SWC 28cm')) + # Fixed to 3_1_1.c
  scale_y_continuous(limits = c(0, 100), name = expression('% VWC')) + 
  scale_x_datetime(limits = as.POSIXct(biomet_dates)) + 
  theme_bw()
```

# Save

```{r, warning=FALSE}
df <- df[!duplicated(df$TIMESTAMP), ]

df$TIMESTAMP <- format(as.POSIXct(df$TIMESTAMP), format ="%Y-%m-%d %H:%M" )
df$ts = format(as.POSIXct(df$ts), format ="%Y-%m-%d %H:%M")
write.csv(x = df,file = 'C:/Users/klynoe/Documents/toolik/R_outputs/met/flux_met_tms_c_2025_2026.csv',row.names = F,quote = T)

```

# Save as individual month

```{r, warning = F}

base_path = "C:/Users/klynoe/Documents/toolik/R_outputs/met/"


met <- met %>%
  mutate(
  TIMESTAMP_fixed = sub("(\\d{4}-\\d{2}-\\d{2}) (\\d{2})(\\d{2})", "\\1 \\2:\\3", TIMESTAMP),
   TIMESTAMP = as.POSIXct(TIMESTAMP_fixed, format = "%Y-%m-%d %H:%M", tz = "UTC")
 )

data_nested = met %>%
  mutate(TIMESTAMP = as.POSIXct(TIMESTAMP, format = "%Y-%m-%d %H:%M:%S")) %>%
  mutate(year_month = format(TIMESTAMP, "%Y%m")) %>%
  group_by(year_month) %>%
  nest() %>%
  ungroup() %>%  # Important to prevent errors with grouped data
  mutate(file_path = paste0(base_path, "toolik_gth89_biomet_", year_month, ".csv"))

walk2(
  .x = data_nested$data, 
  .y = data_nested$file_path, 
  ~ {
    # Ensure the nested data frame has the same column names and types as units_row
    .x[] = lapply(.x, as.character)  # Convert all columns to character
    
    # Write to CSV
    write.csv(.x, .y, row.names = FALSE)
  }
)



#knitr::opts_chunk$set(echo = TRUE)
```





